apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-resources
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: fiztehno/online_inference:v2
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "10Gi"
          cpu: "500m"
